<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>iot_robot_mujoco</name>
    <version>0.1.0</version>
    <description>MuJoCo simulation of the iot_robot using mujoco_ros2_control.</description>
    <maintainer email="6638050521@student.chula.ac.th">tawan</maintainer>
    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>iot_robot_description</exec_depend>
    <exec_depend>mujoco_ros2_control</exec_depend>
    <exec_depend>twist_mux</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>