twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      teleop:
        topic: cmd_vel/teleop
        timeout: 1.0
        priority: 100
      follower:
        topic: cmd_vel/follower
        timeout: 0.5
        priority: 10
